const IMG = "https://harriotwatches.com/roma/img/211830/";
module.exports = {
  slug: "amitech-hands",
  order: 3,
  category: "Craft",
  title: "There Is a Craftsman Behind Even a Single Hand",
  titleSuffix: "The Amitech story",
  dek: "“Do you know how many processes go into making one watch hand? People say ‘it’s only a hand’, and that is the sad part.”",
  description: "A precision shop in Incheon that makes semiconductor moulds and medical devices also makes watch hands. On balance, on the hundredth of a millimetre, and on why they ran the machines twenty-four hours.",
  keywords: "korean watch, watch hands, Amitech, precision manufacturing, made in Korea, HARRIOT",
  date: "2026-06-12",
  hero: IMG + "revival_01.jpg",
  heroAlt: "The head of Amitech seated at precision machining equipment inside the workshop, on the telephone.",
  image: IMG + "revival_01.jpg",
  alt: "Precision machining equipment inside the Amitech workshop",
  blocks: [
    { t:"lede", text:"A wristwatch needs parts sourced at many separate stages. The factory clusters of China and the large Swiss houses hold most of that under one roof. In Korea it is dials in one place, hands in another, assembly in a third — every step found on foot." },
    { t:"p", text:"Introduced by Jang In-cheon of Sungwoo Precision, we went to see Kim Ha-beom of Amitech in Incheon. Watch hands are not, in fact, this company’s main business." },
    { t:"p", text:"“The gap between Korea and the global watch manufacturing market is already wide. Jumping into that race head-on, I don’t think we win. So I wanted to approach it differently. What we actually have is advanced precision work — semiconductor moulds, medical devices, automotive engine parts. We gathered the people who used to make watch hands, and we are growing it back, slowly.”" },
    { t:"p", text:"Because Amitech’s equipment handles work finer than a watch hand, the shop is in fact better equipped than firms that make nothing else. That is why the quality can be trusted." },
    { t:"h2", text:"Everything comes down to balance" },
    { t:"quote", text:"The most important thing in a watch hand is the balance point. One side is far longer than the other, so you are thinning something already thin while holding both its shape and its centre.", cite:"Kim Ha-beom, Amitech" },
    { t:"p", text:"Ordering through a Chinese factory usually means choosing from options that already exist, unless the volume is very large. Fast supply and proven quality are real advantages, but getting your own design into production takes considerable effort. Kim works every day to change that — guaranteeing each client’s design and quality even in small quantities." },
    { t:"p", text:"“It sounds funny, but I suspect a foreign watch brand’s factory makes hands for eight or nine hours a day. We have run twenty-four hours to get through the variety of work, and there is no shape or design we have not tried. I am confident we are not behind. Ha.”" },
    { t:"img", src: IMG+"revival_05.jpg", alt:"A watch hand machining process running on precision equipment at Amitech.", cap:"On the day we visited, a line was running seconds hands destined for Rolex." },
    { t:"p", text:"Korean clients, he says, tend to weigh unit price and lead time more heavily than a hundredth of a millimetre. The Swiss would not allow that hundredth, and checked it with their own eyes. Watching that, he resolved to hold his own pride and push the work further." },
    { t:"h2", text:"How we want to grow" },
    { t:"p", text:"“A watch is art, and so is making a single hand. We have the equipment and the skill for other processes too, but they don’t pay, so you cannot simply start. It needs sustained investment and sustained demand.”" },
    { t:"p", text:"Switzerland and Japan supply movements at reasonable prices and in volume, which makes it hard for anyone to arrive late. The gap widens, and the received wisdom becomes: forget the core technology, worry about everything around it. Meanwhile China absorbs the know-how of Korean technicians and moves forward while Korea falls behind." },
    { t:"quote", text:"Start with what we are already good at, build scale, and expand from there. That is how the industry gets handed down.", cite:"Kim Ha-beom, Amitech" },
    { t:"p", html:"<strong>Sungwoo Precision</strong> for dials, <strong>Mullae Watch</strong> for cases, <strong>Amitech</strong> for hands. A HARRIOT watch passes through the hands of people who have each held one part of Korean watchmaking open. We are trying to bring it back, slowly." },
    { t:"end" },
    { t:"note", text:"Adapted from a piece published on the HARRIOT blog in 2018, introducing the craftspeople who work with us." },
  ],
  cta: { href:"/journal/sungwoo-dial.html", label:"Read next", name:"The Man Who Shapes the Face of a Watch",
    desc:"Thirty-six years of dials at Sungwoo Precision.", go:"Continue reading" },
};
