const IMG = "https://harriotwatches.com/roma/img/211830/";
module.exports = {
  slug: "dobo-2018",
  order: 1,
  category: "Heritage",
  title: "Setting 27 April 2018 on a Wrist",
  titleSuffix: "Making the Dobo Edition",
  dek: "On the day two leaders sat down together on the footbridge at Panmunjom, we stopped editing and stood in front of the television. Then one sentence changed the air in the office.",
  description: "How the 2018 inter-Korean summit at the Panmunjom footbridge became a watch: the blue at four o’clock, the 27 in the date window, the F for Friday, and 500 pieces.",
  keywords: "korean watch, Panmunjom, inter-Korean summit, limited edition watch, Dobo, HARRIOT, made in Korea",
  date: "2026-06-12",
  hero: IMG + "dobo_01.jpg",
  heroAlt: "Two leaders seated on a bench on the blue footbridge at Panmunjom, the bridge running through woodland.",
  image: IMG + "dobo_01.jpg",
  alt: "Two leaders seated on the footbridge at Panmunjom",
  blocks: [
    { t:"lede", text:"27 April 2018. We were cutting an interview with Jang In-cheon of Sungwoo Precision for HARRIOT’s first crowdfunding campaign. We stopped, and stood in front of the television for a long time. Across the country, most people were doing the same." },
    { t:"p", text:"Then one sentence changed the air in the office." },
    { t:"quote", text:"On a day the whole world is watching — a day about being proud of what Korea makes — isn’t there something we could do? What if we took the footbridge as the starting point?", cite:"Sungjo Hong, founder of HARRIOT" },
    { t:"p", text:"“The Seongsan collection isn’t even finished yet.” “Isn’t this too much?” “What footbridge?” Not everyone agreed at first." },
    { t:"p", text:"“Maybe it is precisely because we are a Korean brand that we can try it. If we make it, I want one myself. I want to give them away, too.”" },
    { t:"p", text:"There was also a habit we had already formed. Brands often name products after a city, a figure, or an event. HARRIOT, asking what Korean design might mean, had arrived at bridges." },
    { t:"p", text:"A bridge is necessary from antiquity to the present, cannot be built without serious engineering, and holds aesthetic value simply by existing — which is exactly what we want a watch to be. A meaningful spring in 2018, and a bridge whose name means, literally, foot bridge. The Dobo collection began there." },
    { t:"img", src: IMG+"dobo_05.jpg", alt:"Close view of the HARRIOT Dobo Edition dial.", cap:"The Dobo dial. Blue appears in three places, and nowhere else." },
    { t:"h2", text:"So how do you design a date?" },
    { t:"p", html:"Friday, 27 April 2018. To put that date on a dial, the team found three points: <strong>the index at four o’clock, the 27 in the date window, and the F for Friday.</strong> Those three, and only those three, would carry the blue of the footbridge." },
    { t:"p", text:"The difficulty was that this blue is not the blue normally used on indices or seconds hands. Getting the colour out was the whole problem. Too little and it disappears; too much and it turns heavy. Sample after sample was made just to settle the colour of a single index at four o’clock. It was the skill and long practice of the dial maker at Sungwoo Precision that finally produced something we were happy with." },
    { t:"h2", text:"If it is a keepsake, make it like one" },
    { t:"p", text:"A colour accent alone does not make a watch special, or limited. We decided to push quality as far as we could: sapphire crystal for the glass, a crocodile-pattern strap, and a butterfly clasp that does not damage the leather over time." },
    { t:"p", text:"The box, the warranty card and the manual were all redesigned for this edition alone. The dial was given a textured pattern to set it apart from the Seongsan collection, and Korea Made was printed at six o’clock." },
    { t:"duo", items:[
      { src: IMG+"dobo_08.jpg", alt:"The engraved limited-edition number on the caseback of the Dobo Edition.", cap:"Each caseback was numbered, and the same number written on the warranty card." },
      { src: IMG+"dobo_09.jpg", alt:"The Dobo Edition presentation box and warranty documents.", cap:"Box, warranty and manual, made for this edition only." } ] },
    { t:"p", html:"<strong>Five hundred pieces</strong> of Dobo went out into the world, and every one of them found an owner." },
    { t:"h2", text:"Wasn’t there a watch factory at Kaesong?" },
    { t:"p", text:"There was. The Kaesong Industrial Complex, idle since 2016, held the factories that made most of Korea’s watches. After it closed, most Korean watch production moved to China and elsewhere, bringing a language barrier, shipping costs and lead times with it." },
    { t:"p", text:"For the sake of the industry itself, we hope that dying ember catches again. If a bridge is what joins two separated places, HARRIOT wanted to leave that hope on a wrist." },
    { t:"end" },
    { t:"note", text:"Adapted from a piece published on the HARRIOT blog in 2018, when the Dobo Edition was introduced. The edition was limited to 500 pieces and is no longer available." },
  ],
  cta: { href:"/category/collection/43/", label:"Collection", name:"HARRIOT Collections",
    desc:"Watches named after Korean bridges — Gayang, Gwangan, Seohae, Seongsan, and KI:WON.",
    go:"View collections" },
};
