const IMG = "https://harriotwatches.com/roma/img/211830/";
module.exports = {
  slug: "kari-757",
  order: 0,
  category: "Heritage",
  title: "757 Watches That Waited for Nuri",
  titleSuffix: "HARRIOT × Korea Aerospace Research Institute",
  dek: "A watch brand cold-called the national space agency. It took a month to reach the right person, and three months to sign.",
  description: "How a Korean watch brand partnered with the Korea Aerospace Research Institute after the 2018 test launch, and why exactly 757 moon-phase watches were made — a number taken from two rocket engines.",
  ogDescription: "75 tonnes and 7 tonnes — two engines, one number engraved into 757 watches. In 2022, Nuri reached orbit.",
  keywords: "korean watch, Nuri rocket, KSLV-II, Korea Aerospace Research Institute, KARI, moon phase watch, HARRIOT, made in Korea",
  date: "2026-06-12",
  hero: IMG + "kari_01.jpg",
  heroAlt: "The KSLV-II test launch vehicle standing on the pad at Naro Space Center in Goheung, silhouetted against an evening sky.",
  image: IMG + "kari_01.jpg",
  alt: "Test launch vehicle on the pad at Naro Space Center",
  blocks: [
    { t:"lede", text:"On 28 November 2018, a test launch vehicle lifted off successfully from the Naro Space Center in Goheung, on Korea’s southern coast. With it, Korea became the seventh country in the world to build its own liquid-fuel rocket engine." },
    { t:"p", text:"For one listener catching the news on the radio, what lingered was less pride than a question. Does Korea have a place that researches this? Didn’t we launch something called Naro before? Is it a Korean NASA?" },
    { t:"p", text:"The Korea Aerospace Research Institute — KARI — is a government-funded research institute founded to advance aerospace science for the public good. At the time it was running the country’s largest space programme: Nuri, or KSLV-II, a launch vehicle built entirely with Korean technology." },
    { t:"p", text:"So why is such an institution unfamiliar to most Koreans? NASA has jackets and mugs and patches. It feels like a neighbour. KARI did not." },
    { t:"img", src: IMG+"kari_04.jpg", alt:"A press briefing following the successful test launch. The screen behind reads ‘Space independence, the first step of the engine’, beside the logos of the Ministry of Science and ICT and KARI.", cap:"The briefing on 28 November 2018. The screen read: “Space independence — the first step of the engine.”" },
    { t:"quote", text:"So let’s be the ones who do it. If not us, what watch brand would?", cite:"Sungjo Hong, founder of HARRIOT" },
    { t:"h2", text:"A month to reach the right person" },
    { t:"p", text:"HARRIOT simply called. It did not go smoothly. Among busy researchers it was hard even to work out which department to ask for. Reaching the person who could actually say yes took, without exaggeration, a month." },
    { t:"p", text:"“Could you send us a business plan and a commercialisation plan?”" },
    { t:"p", text:"Eleven pages of company introduction and product planning went out. After several weeks of waiting, the researcher wrote back." },
    { t:"p", text:"“Honestly, we never expected a call like this. Our president is looking forward to it, and asked me to pass on his thanks. We looked at how hard you have worked to make watches in Korea, and the products you have released — and decided you are a company we could make something worthy with.”" },
    { t:"p", text:"The researcher travelled from Daejeon to the HARRIOT office in Seoul in person. From first idea to signature on the agreement took three months." },
    { t:"img", src: IMG+"kari_15.jpg", alt:"The Nuri launch vehicle lying horizontally in an assembly building, its white body marked with the Korean flag and the words ‘Republic of Korea’, with yellow work stairs alongside.", cap:"Nuri (KSLV-II) in the assembly building. Three months of talks were about making a keepsake for this rocket." },
    { t:"h2", text:"Exactly 757, and why" },
    { t:"p", html:"The heart of the test programme was two engines: a <strong>75-tonne engine and a 7-tonne engine</strong>. Those two engines put Korea among the spacefaring nations. HARRIOT took the number straight from them. <strong>757 watches.</strong> Not one more." },
    { t:"p", text:"Each caseback carried its own number, from 1 to 757, laser-engraved alongside whatever the owner asked for. A name, a private message, a date that mattered. Seven hundred and fifty-seven watches went out carrying seven hundred and fifty-seven different stories." },
    { t:"p", text:"The collection was revealed in November 2019 — one year after the test launch, and KARI’s thirtieth anniversary." },
    { t:"h2", text:"The face of a space watch" },
    { t:"p", html:"The dial is a black moon phase. The caseback carries the limited-edition number and the name Nuri (KSLV-II). Two straps were made: a solid stainless bracelet drawn from the look of spacecraft metal, and a white canvas strap with a hook-and-loop closure, taken from spacesuit design, <strong>fastenable while wearing gloves</strong>. A display stand was included so the watch could sit out as an object even when it was not being worn." },
    { t:"duo", items:[
      { src: IMG+"kari_25.jpg", alt:"Profile view of the KARI collection watch on its stand, showing the black dial and stainless steel bracelet.", cap:"Black moon-phase dial and 316L stainless bracelet." },
      { src: IMG+"kari_30.jpg", alt:"A white canvas hook-and-loop strap on a wrist, with the KARI logo embroidered in blue thread.", cap:"The white canvas strap, drawn from spacesuit design, with the KARI logo embroidered." } ] },
    { t:"h3", text:"Specification" },
    { t:"spec", rows:[
      ["Movement","Swiss Ronda 708 quartz moon phase. With no Korean-made movement available, we chose the Swiss maker used widely in fine watchmaking."],
      ["Crystal","Sapphire with anti-reflective coating. At 2000 Hv it is roughly twice the hardness of the stainless case (about 1000 Hv)."],
      ["Straps","316L stainless steel bracelet / heavy cotton canvas hook-and-loop strap"],
      ["Size","40mm diameter · 20mm lug width"],
      ["Water resistance","5 ATM"],
      ["Battery","362 / SR721SW · accuracy +20 to −10 seconds per month"],
      ["Origin","Made in Korea"] ] },
    { t:"img", w:"bleed", src: IMG+"kari_08.jpg", alt:"The Nuri launch vehicle in flight above Earth orbit, the blue atmosphere curving below.", cap:"On 21 June 2022, Nuri placed a satellite into orbit on its second flight." },
    { t:"h2", text:"And then Nuri reached space" },
    { t:"p", html:"What the watch had wished for came true. On 21 June 2022, Nuri’s second flight placed a satellite into orbit, making Korea the <strong>seventh country able to launch a practical satellite with its own rocket</strong>. A third successful flight followed in 2023." },
    { t:"p", text:"Seven hundred and fifty-seven wrists were watching. HARRIOT intends to remember that." },
    { t:"end" },
    { t:"note", text:"Adapted from a piece first written in late 2019, when the KARI collection was introduced through crowdfunding. The KARI collection was limited to 757 pieces and is no longer available." },
  ],
  cta: { href:"/seolwol/", img: IMG+"kari_24.jpg", alt:"A HARRIOT moon-phase watch on a display stand",
    label:"Continue", name:"Seolwol — The Moon of Your Night",
    desc:"The complication we put on a space watch carries into the next one. Tell us a night you still remember, and we will find the moon that hung over it.",
    go:"Find your moon" },
};
