/* Source: Naver blog harriotwatches/223756795733 (11 Feb 2025, written by founder Sungjo Hong). */
const IMG = "https://harriotwatches.com/journal/img/";
module.exports = {
  slug: "kiwon",
  order: 6,
  category: "Craft",
  title: "How to Put a National Flag on a Dial",
  titleSuffix: "Making KI:WON",
  dek: "The taegeuk, or the four trigrams? That was the question we held longest in front of the first watch we had made in five years.",
  description: "KI:WON, HARRIOT’s first watch in five years. How the Korean flag became a watch without becoming a souvenir: the trigrams moved into the index positions, and the rose of Sharon hidden in a fan pattern.",
  ogDescription: "We did not put the taegeuk on the dial. We moved the four trigrams into the index positions and hid the rose of Sharon in a fan pattern.",
  keywords: "korean watch, KI:WON, HARRIOT, Korean flag watch, taegeukgi, four trigrams, made in Korea",
  date: "2025-02-11",
  hero: IMG + "kiwon_01.jpg",
  heroAlt: "The KI:WON black dial on a black background. The four trigrams of the Korean flag sit in the index positions, with a fine repeating pattern across the centre of the dial.",
  image: IMG + "kiwon_01.jpg",
  alt: "KI:WON black dial, with the trigrams in the index positions",
  blocks: [
    { t:"lede", text:"This is KI:WON, the first watch HARRIOT has made in five years. Something had frustrated me through all the watches before it. I always knew what watch I wanted to make and what story I wanted it to hold — but I did not have the expertise to turn that into an object." },
    { t:"p", text:"Then a good introduction led to a collaboration. HARRIOT took the planning, the story and the overall concept; Aperture took the design. The specifics were settled between us, but the division was clear: concept with us, design with them." },
    { t:"h2", text:"The taegeuk, or the trigrams" },
    { t:"p", text:"The watch takes the Korean flag as its motif. The difficulty was deciding what to emphasise: the taegeuk itself — that vivid red and blue circle everyone pictures first — or the four trigrams, geon, gon, gam and ri." },
    { t:"p", text:"The taegeuk is striking and beautiful, but placing it directly on a small round dial is a heavy gesture. The trigrams, by contrast, are arrangements of lines, which makes them far easier to vary. That is why many flag-inspired designs use them — and why it is also hard to do anything distinctive with them." },
    { t:"quote", text:"Even with the flag as the motif, we must not lose the point: this has to be a good watch.", cite:"Sungjo Hong, founder of HARRIOT" },
    { t:"p", text:"A watch is more interesting when what you see at a glance and what you see up close are not the same thing. So this one was designed so that you might not notice the flag at first — and then, looking slowly, find what has been hidden in it." },
    { t:"img", src: IMG+"kiwon_02.jpg", alt:"The KI:WON dial photographed at an angle, showing the trigram indices, the repeating central pattern and the applied index rim.", cap:"An ordinary texture from a distance. The symbol of a flag up close." },
    { t:"h2", text:"Four things hidden in it" },
    { t:"h3", text:"The trigrams" },
    { t:"p", text:"Placed exactly where they sit on the flag, then adjusted so they do not feel foreign beside the other indices." },
    { t:"h3", text:"The centre pattern" },
    { t:"p", text:"A small repeating trigram motif runs across the centre of the dial. At arm’s length it reads as texture. Closer, the symbol appears." },
    { t:"h3", text:"The rose of Sharon" },
    { t:"p", text:"The flag alone risked being monotonous, so we looked for an object that sits well with it. A fan-shaped pattern suggesting the petals of the rose of Sharon — Korea’s national flower — was added outside the index rim. The shape is common enough in watch design; the intent was to join the flower and the flag." },
    { t:"h3", text:"The index rim" },
    { t:"p", text:"The rim was made separately and applied, so the dial reads as more dimensional and more considered." },
    { t:"p", text:"For the record, we did try simplifying the taegeuk itself, several times. Nothing met the standard of being a good watch first, so all of it was discarded." },
    { t:"duo", items:[
      { src: IMG+"kiwon_04.jpg", alt:"The KI:WON black dial and white dial side by side on a black background.", cap:"Two dials, black and white." },
      { src: IMG+"kiwon_06.jpg", alt:"The KI:WON white dial at an angle, the navy trigram indices clearly visible.", cap:"On the white dial the trigrams come forward." } ] },
    { t:"h2", text:"What we dropped from the case, and what we kept" },
    { t:"p", text:"Cutting new tooling opened up the case as well. We considered setting the HARRIOT mark — the Independence Gate — near the crown, but the finishing was difficult and it added thickness, so it did not make the final design." },
    { t:"p", html:"Instead the case stays simple, with <strong>a slightly wider mid-case</strong> and the bevel along its flank carried through into the lugs — an approach used on some Omega models. Paired with the flat sapphire crystal, the intention was for the watch to look more graceful, and more curved, seen head-on." },
    { t:"img", src: IMG+"kiwon_05.jpg", alt:"Profile of the KI:WON case, showing the bevel running from the mid-case into the lugs.", cap:"The bevel on the mid-case flank continues into the lugs." },
    { t:"h3", text:"Specification" },
    { t:"spec", rows:[
      ["Case","37mm diameter"],
      ["Movement","Ronda 762 quartz, two hands, no date"],
      ["Crystal","Sapphire with anti-reflective and anti-fingerprint coating"],
      ["Water resistance","50m (WR50)"],
      ["Dial","Black / white"],
      ["Design","Concept by HARRIOT · design by Aperture"] ] },
    { t:"p", text:"No significant design changes remain — only small refinements, such as sharpening the texture on the index rim. We are also planning the packaging, and a particular gift to go with it." },
    { t:"p", text:"Thank you for waiting so long." },
    { t:"end" },
    { t:"note", text:"Adapted for the journal from a post written by founder Sungjo Hong on 11 February 2025, ahead of the watch’s release. KI:WON launched as planned and is available now." },
  ],
  cta: { href:"/product/list.html?cate_no=42", img: IMG+"kiwon_04.jpg", alt:"KI:WON in black and white",
    label:"The watch", name:"KI:WON",
    desc:"The Korean flag as motif, without overstating it. 37mm · sapphire crystal · 50m water resistance.",
    go:"See KI:WON" },
};
