/* English edition of the Korean journal article articles/ko/seolwol.js.
   Written as an English piece in the founder's voice, not a translation.
   No price: the global figure is USD 350 but shipping is DDU, so a bare number
   understates what the customer actually pays on arrival. Price lives on the product page. */
const IMG = "https://harriotwatches.com/journal/img/";
module.exports = {
  slug: "seolwol",
  order: 1,
  lead: true,
  category: "Craft",
  title: "A Moon That Crosses a Roof, Once a Month",
  titleSuffix: "Making SEOLWOL",
  dek: "Almost every moonphase changes the shape of the moon. Ours changes where it sits. The moon is always full, and it spends a month crossing a roof.",
  description: "SEOLWOL 雪月 — a Korean moonphase watch whose aperture is cut along the curve of a hanok eave. The moon stays full; what changes is its place on the roof. How the disc was drawn and made in Korea.",
  ogDescription: "The moon stays full. Over a month it crosses a hanok roof and sets behind the far eave. SEOLWOL, 10 September.",
  keywords: "korean watch, SEOLWOL, HARRIOT, moonphase watch, hanok, made in Korea, custom moon disc",
  date: "2026-09-10",
  hero: IMG + "seolwol-01-dial-window.jpg",
  heroAlt: "Macro of the SEOLWOL dial. The moon sits half-caught between the eaves in the aperture at twelve o'clock.",
  image: IMG + "seolwol-01-dial-window.jpg",
  alt: "SEOLWOL dial, moon half-caught between the eaves",
  blocks: [
    { t:"lede", text:"A new watch is coming. Its name is SEOLWOL — 雪月, snow and moon in one word. I made it thinking of the deepest part of winter: a night after the snow has stopped, and a moon over the eaves of a hanok roof where the snow has settled." },
    { t:"p", text:"Today I want to write down what I was thinking while we made it." },

    { t:"h2", text:"It began with one photograph" },
    { t:"img", src: IMG+"seolwol-02-hanok-eaves-snow.jpg",
      alt:"Snow settled on the tiled roofs of a hanok village, the eave curve running across the frame.",
      cap:"Sunlight on the settled snow, giving off a colour that was neither white nor sky-blue." },
    { t:"p", text:"It began with a photograph I came across by chance." },
    { t:"p", text:"It looked like a hanok village. In it were tiled roofs holding snow, and where the light touched them they were giving off a strange colour — not white, not sky-blue, but somewhere between the two." },
    { t:"p", text:"The colour was beautiful." },
    { t:"p", text:"The curve of the eaves and that bluish cast were so strong that I decided I would one day make a watch out of them." },
    { t:"p", text:"SEOLWOL began in that one photograph. The colour of the roof became the dial. The curve of the eave became the aperture and the indices." },

    { t:"h2", text:"We have never simply looked at the moon" },
    { t:"p", text:"When we say we are looking at the moon, we are not only looking at the sky. Stand in a courtyard and the roofline cuts the sky first. The moon always hung at the end of that curve." },
    { t:"p", html:"So what we remember is not the moon. It is <strong>the moon seen together with the eaves</strong>." },
    { t:"p", text:"That is why the aperture at twelve o'clock has the shape it has. We cut it along the eave line of a hanok roof. The moon rises between those eaves, and sets behind them." },

    { t:"h2", text:"The moon neither waxes nor wanes" },
    { t:"img", src: IMG+"seolwol-03-eaves-aperture.jpg",
      alt:"Close view of the moonphase aperture. The two arcs below the window flow outward rather than cutting inward.",
      cap:"We cut the two arcs below the window to flow outward instead of in — the roofline as you see it from the courtyard." },
    { t:"p", html:"In most moonphase watches the <strong>shape</strong> of the moon changes day by day. Crescent, half, full." },
    { t:"p", text:"That is done with two arcs that cut inward from below the window. Those arcs shave the sides of the moon and make the phases. Nearly every moonphase is built this way." },
    { t:"p", html:"<strong>The moon in SEOLWOL is always full.</strong>" },
    { t:"p", html:"What changes instead is <strong>where on the roof it is hanging</strong>." },
    { t:"p", text:"To do that we cut those two arcs the other way. Rather than biting inward, they flow outward — exactly the roofline you see looking up from a courtyard." },
    { t:"p", text:"The moon rises at one eave, crosses the roof, and sets behind the eave on the other side. Once over the course of a month." },
    { t:"p", html:"A moon half-covered does not read as a half moon. The line hiding it is not a round arc carving into it, but the outward curve of an eave. It reads not as a phase but as <strong>a moon behind a roof</strong>." },
    { t:"p", text:"I should be honest about the cost of this. Because we removed the arcs that made the phases, there is a stretch once a month when the setting moon and the rising moon sit in the window together." },
    { t:"p", text:"We did not do it without knowing. Phases exist on every moonphase there is. A moon crossing a roof exists only here." },

    { t:"h2", text:"We drew the moon again" },
    { t:"img", src: IMG+"seolwol-16-movement-stock.jpg",
      alt:"The RONDA 708 movement before customisation, with its original moon disc visible.",
      cap:"The movement before we touched it. The moon in there was not the moon I had seen." },
    { t:"p", text:"A movement comes with a moon already in it. You can use it as it is. Most do." },
    { t:"p", text:"But that moon was not the moon I had seen." },
    { t:"p", text:"The moon I remember was not yellow. It was closer to a moon jar — white with a blue cast, a grey-blue." },
    { t:"p", text:"I wanted that colour. And I wanted that moon to be the one thing still lit when the lights went out." },
    { t:"p", text:"There was nowhere that would make it." },
    { t:"p", text:"When I said I wanted a moonphase disc made from scratch, everyone was at a loss. Even a man who had made nothing but dials in Korea for decades told me he had never once done it." },
    { t:"p", text:"HARRIOT is made in Korea. I know that is the biggest reason people care about us. But making things here means you will sometimes have to ask for something nobody has done. This was one of those times." },
    { t:"p", text:"Persuading was work in itself. So was finding where to begin." },
    { t:"p", text:"There are people who have stayed beside me for a long time. Each of them told me one thing they knew, and when I put those pieces together a way through finally appeared. I could not have done it alone." },
    { t:"p", text:"So we were able to make the disc." },
    { t:"p", text:"We drew the moon and the stars again and gave the surface of the moon a grain. Not a smooth circle, but a moon with the blemishes only someone who has looked up for a long time knows." },
    { t:"img", src: IMG+"seolwol-13-lume-closeup.jpg",
      alt:"A moon disc glowing blue in the dark, two moons visible on the single disc.",
      cap:"With the factory lights off. There are two moons on each disc." },
    { t:"p", text:"And we put lume on the moon alone. Turn the lights off and the hands and indices disappear; only the moon remains." },
    { t:"p", text:"Once one moon has crossed the roof over the course of a month, another comes up on the far side." },
    { t:"img", src: IMG+"seolwol-15-moondisc-jig.jpg",
      alt:"A moon disc on a machining jig. Two white moons and stars of differing sizes are printed on a deep navy ground.",
      cap:"With the lights on. The stars are deliberately different sizes — so that near stars and far stars share one sky." },

    { t:"h2", text:"Where the moons are made" },
    { t:"img", src: IMG+"seolwol-10-dial-tray.jpg",
      alt:"Around fifty SEOLWOL dials laid out in a tray, the eave-shaped apertures repeating across the frame.",
      cap:"You only see it once fifty are laid out together — that the two arcs below the window flow outward rather than in." },
    { t:"p", text:"I went out to the workshop that makes the dials and the moon discs a few times." },
    { t:"p", text:"Laid out in a tray they look like this. In the drawing it was one curve; here it is the same curve fifty times over. You can see the grain on the surface too. It does not photograph well, but in the hand it is obvious." },
    { t:"img", src: IMG+"seolwol-11-moondisc-complete.jpg",
      alt:"Finished moon discs collected in a tray after the ground, the moons and the stars have been printed.",
      cap:"The ground goes down, then the moon, then the stars." },
    { t:"p", text:"A moon disc is not finished in one pass. I looked at this photograph for a long time. Each one of them is a moon that will rise once a month on somebody's wrist." },
    { t:"p", text:"It may not amount to much. Still, there is now at least one place in Korea that has made one of these. The next person who wants to try will not have to start the persuading from the beginning." },

    { t:"h2", text:"Twelve eaves" },
    { t:"img", src: IMG+"seolwol-05-index-snow.jpg",
      alt:"Macro of the applied indices. Each bar rises at the shoulders and dips in the centre.",
      cap:"Shoulders up, centre down. Exactly the roof you see looking up from a courtyard." },
    { t:"p", text:"Nobody is ever going to ask me about this. I want to write it down anyway." },
    { t:"p", text:"The bars that mark the hours are called indices. Usually they are flat rectangular bars. That is easy, it is quick, and it is what most watches do." },
    { t:"p", text:"We drew the indices of SEOLWOL again from the technical drawing up." },
    { t:"p", text:"Four millimetres long. Both ends cut back at fifteen degrees, and the span between them hollowed into a curve, so the centre sits lower than the ends." },
    { t:"p", html:"Why do that? <strong>Because that line is the line of an eave.</strong> Shoulders rising, centre dipping. It is exactly the roof you see looking up from a courtyard. One aperture at twelve was not enough. I wanted the shape laid across the dial twelve more times." },
    { t:"p", text:"Then something I had not expected followed. Light." },
    { t:"p", html:"A flat index flashes once at one angle and goes out. A concave face does not. Tilt the wrist a little and the light runs along the curve. Instead of going out, it <strong>moves</strong>." },
    { t:"p", text:"We killed as much shine as we could on the dial. So the only thing throwing light back is the indices." },
    { t:"p", text:"It is like sunlight landing on a snowfield. The ground stays quiet, and only the glitter moves." },

    { t:"h2", text:"The colour of snow" },
    { t:"p", text:"Settling the dial colour took the longest." },
    { t:"p", text:"I had to build again the colour I saw the first time in that photograph, and it was not easy." },
    { t:"p", text:"Snow is not white. Snow lying in shade carries a very faint blue. Photographs usually record it as white, but stand on it and you know." },
    { t:"p", html:"The dial of SEOLWOL is that colour. Not white — <strong>the colour of a roof with snow on it</strong>." },
    { t:"p", text:"We worked the texture for a long time as well. Snow does not shine. It holds. So we left the surface holding the light rather than returning it." },

    { t:"h2", text:"A second that does nothing" },
    { t:"img", src: IMG+"seolwol-04-secondhand-align.jpg",
      alt:"The seconds hand at twelve, its counterbalance carrying the HARRIOT symbol resting over the logo at six.",
      cap:"Once a minute, the watch composes itself." },
    { t:"p", text:"We put the HARRIOT symbol on the short tail of the seconds hand." },
    { t:"p", text:"The moment the hand touches twelve, the symbol on the opposite end comes to rest over the logo at six. They become a single line through the middle of the dial." },
    { t:"p", text:"Once a minute, the watch composes itself." },
    { t:"p", text:"It is a second that does nothing. The time is no more accurate for it, and no easier to read. Even so, I redrew the shape of that hand several times to make it." },

    { t:"h2", text:"It took a long time" },
    { t:"img", src: IMG+"seolwol-08-strap.jpg",
      alt:"Navy crocodile-pattern calf strap, tapering from twenty to sixteen millimetres.",
      cap:"Navy crocodile-pattern calf. Twenty millimetres tapering to sixteen." },
    { t:"p", text:"Most of the time we spent making it, we spent waiting." },
    { t:"p", text:"A sample arrives, we check it, we change what is wrong, we wait again. More than once we spent days on a tenth of a millimetre. Something is right on the drawing and different in the metal, and then you start looking from the beginning." },
    { t:"p", text:"Honestly, most of it is difference nobody will notice." },
    { t:"p", html:"But enough of those differences stack up and they turn into the words &ldquo;I do not really know why, but I like it.&rdquo; Those are the words I am doing this to hear." },

    { t:"h2", text:"Coming soon" },
    { t:"img", src: IMG+"seolwol-06-topdown.jpg",
      alt:"SEOLWOL seen from directly above, on a plain ground.",
      cap:"SEOLWOL 雪月 · 38mm · 8.15mm thick" },
    { t:"p", html:"SEOLWOL arrives on <strong>10 September</strong>." },
    { t:"p", text:"Thirty-eight millimetres across, 8.15 millimetres thick — thin enough to slide under a shirt cuff. The strap is navy crocodile-pattern calf." },
    { t:"img", src: IMG+"seolwol-09-caseback.jpg",
      alt:"The caseback. The centre is left as a bare circle for engraving, ringed by the grain of a hanok roof.",
      cap:"The centre is left open. Engraving is free, and it does not delay dispatch." },
    { t:"h3", text:"There is a moon on the back as well" },
    { t:"p", text:"We put one more moon on the caseback. The centre of the back is left as a bare circle, ringed by the grain of a hanok roof. The moon that crossed the aperture is up once more, on the inside of the wrist." },
    { t:"p", text:"The engraving goes inside that open moon. A name, a date, or nothing at all. Engraving is free, and adding it does not change the dispatch date." },
    { t:"h3", text:"Specification" },
    { t:"spec", rows:[
      ["Model","HARRIOT SEOLWOL 雪月"],
      ["Case","38mm · 8.15mm thick · 316L stainless steel"],
      ["Movement","Swiss RONDA 708 quartz moonphase"],
      ["Crystal","Flat sapphire · internal anti-reflective / external anti-fingerprint coating"],
      ["Dial","Pale sky blue · fine snow texture"],
      ["Indices","Applied bars · 4.0mm · ends cut at 15° · concave centre (eave curve) · polished"],
      ["Moonphase","Twelve o'clock · aperture cut to a hanok eave curve · custom disc (deep navy, two moons) · lume on the moon only"],
      ["Date","Six o'clock"],
      ["Strap","Navy crocodile-pattern calf · 20 → 16mm taper · pin buckle with HARRIOT engraving"],
      ["Caseback","Solid · circular engraving field at centre · hanok roof grain around it"],
      ["Warranty","2 years"],
      ["Engraving","Free · no added lead time"],
    ] },
    { t:"p", text:"I have stood in a courtyard on a night after the snow stopped and looked up at the moon between the eaves." },
    { t:"p", text:"I wanted to keep that night on the wrist." },
    { t:"img", src: IMG+"seolwol-07-angle.jpg",
      alt:"SEOLWOL at an angle, showing the thinness of the case and the curve of the lugs.",
      cap:"SEOLWOL 雪月 — HARRIOT" },
    { t:"end" },
  ],
};
