const IMG = "https://harriotwatches.com/roma/img/211830/";
module.exports = {
  slug: "sungwoo-dial",
  order: 2,
  category: "Craft",
  title: "The Man Who Shapes the Face of a Watch",
  titleSuffix: "Thirty-six years at Sungwoo Precision",
  dek: "We heard there was someone in Seongsu-dong who had given thirty-six years to making watch dials in Korea, and nothing else.",
  description: "Thirty-six years making watch dials in Korea. Jang In-cheon of Sungwoo Precision on the boom of the 1980s, the seven people left in his workshop, and why he never switched to cheaper material.",
  keywords: "korean watch, watch dial maker, Sungwoo Precision, Korean craftsmanship, made in Korea, HARRIOT",
  date: "2026-06-12",
  hero: IMG + "sungwoo_01.jpg",
  heroAlt: "Old dies and hand tools used in watch dial making, laid out in a tray on a workbench.",
  image: IMG + "sungwoo_01.jpg",
  alt: "Old dies and tools used in watch dial making",
  blocks: [
    { t:"lede", text:"“You could have it stamped cheaply in China. Do you really have to make it in Korea?” We were asked that constantly. The answer never changed. “I honestly don’t know whether Korea makes it better than China. But if we are building a Korean watch brand, isn’t it better made in Korea?”" },
    { t:"p", text:"After deciding to make Korean watches, we spent months asking around, half afraid there would be no factories left. We visited and compared workshops. Then we heard there was someone in Seongsu-dong who had given thirty-six years to Korean watch manufacturing, and nothing else." },
    { t:"p", text:"And so the face of every HARRIOT watch is shaped by Jang In-cheon of Sungwoo Precision, one of the very few masters left in the country." },
    { t:"h2", text:"Do you know how good Korea once had it?" },
    { t:"quote", text:"New shops appeared overnight. People you’d never heard of would turn up asking for a few thousand watches. Dealers came with bags of cash — make mine like this, make mine first. There was a time like that.", cite:"Jang In-cheon, Sungwoo Precision" },
    { t:"p", text:"The 1980s were the height of Korean wristwatch manufacturing. Then the market moved toward cheaper production in China, and the factories that remained at Kaesong closed too. Today almost no production line is left in the country." },
    { t:"p", html:"His workshop once employed more than twenty people. <strong>Seven remain.</strong> Selling production equipment worth tens of thousands of dollars to a scrap dealer for a fraction of that, he says, hurt more than he can put into words. His greatest worry now is simple: when he stops, there is no one behind him." },
    { t:"img", src: IMG+"sungwoo_04.jpg", alt:"Dial production under way in the Sungwoo Precision workshop.", cap:"The workshop in Seongsu-dong, where the face of a HARRIOT watch is made." },
    { t:"h2", text:"It is hard to bend a stubbornness like this" },
    { t:"p", text:"“What did twenty years of practising and failing teach me? Cheap material shifts colour too easily and turns yellow. The best Swiss material comes out warm. Once you know that feeling, you cannot use the cheap one just to save a little on cost.”" },
    { t:"p", text:"“But people always say, why are you more expensive? Compare the best in China with the best here and China is far more expensive. They compare us with the worst in China and call us dear. Ha.”" },
    { t:"p", text:"He tried, for the sake of competing on price, every cost reduction there was. In the end he could not bend — not for the quality of the work, and not for the survival of the skill itself. Overlooked as expensive, uncertain about tomorrow, he would not trade thirty years of pride for it." },
    { t:"quote", text:"There is only one of this machine in the country. A magnifier that lets you confirm there is not one unit of error. It is the pride of this workshop.", cite:"Jang In-cheon, Sungwoo Precision" },
    { t:"h2", text:"What Korean-made means" },
    { t:"p", text:"“I think what we make carries something of who we are. Not simply that it is made better — the mindset, the way people think, the national character weighs on it a great deal. When I watch it being made here beside me, I trust it a little more. Though of course the skill has to be there too.”" },
    { t:"end" },
    { t:"note", text:"Adapted from a piece published on the HARRIOT blog in 2018, alongside our first crowdfunding campaign." },
  ],
  cta: { href:"/category/collection/43/", label:"Made by these hands", name:"HARRIOT Collections",
    desc:"Watches wearing dials shaped in Seongsu-dong.", go:"View collections" },
};
